apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.foresee/name: settings-service
  name: settings-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.foresee/name: settings-service
  template:
    metadata:
      labels:
        app.foresee/name: settings-service
    spec:
      containers:
      - name: settings-service
        image: fsr-artifactory.aws.foreseeresults.com:9001/settings-service:{{ index .Values.image.version "settings-service" }}
        imagePullPolicy: IfNotPresent
        env:
        - name: VAULT_URI
          value: {{ .Values.global.env.VAULT_URI }}
        - name: VAULT_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.env.NAME }}-settings-service
              key: vault-role
        - name: VAULT_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.env.NAME }}-settings-service
              key: vault-secret
        - name: K8S_INGRESS_LB
          value: {{ .Values.global.env.K8S_INGRESS_LB }} 
        - name: DEFAULT_JAVA_OPTS
          value: {{ .Values.global.env.DEFAULT_JAVA_OPT }}
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.env.NAME }}-apps-config
              key: settings-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
