---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    testProject: spring-boot-sample
    app: spring-k8s
  name: spring-k8s
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: spring-k8s
  template:
    metadata:
      labels:
        testProject: spring-boot-sample
        app: spring-k8s
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
              #        image: fsr-artifactory.aws.foreseeresults.com:9001/hello-spring-k8s-{{ index .Values.image.tag "spring-k8s" }}:latest
        image: fsr-artifactory.aws.foreseeresults.com:9001/spring-k8s:{{ index .Values.image.version "spring-k8s" }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
